### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by abdelhadi88** [amperose/amperose#1]
Travis CI will be used in this project.
.travis.yml file should be added to take into consideration our CI strategy.

**Comment by Michel-Haber** [comment]
Can we close this?

**Comment by Michel-Haber** [comment]
We already merged the branch concerning this issue.
I think we should close it

**Comment by abdelhadi88** [comment]
Issue will be closed since a (very) basic travis.yml is in place.
Keep in mind that CI should be updated as we the application progresses.
